management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
logging:
  level:
    org.springframework.cloud: debug
    nc.unc.cs.services: debug
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
feign:
  httpclient:
    connection-timeout: 2000
    enabled: false
  okhttp:
    enabled: true
